[package]
name = "exel_to_json"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
calamine = "0.25.0"
serde = { version="1.0.208", features = ["derive"] }
serde_json = "1.0.125"
wasm-bindgen = "0.2.93"
